name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Используем стабильную версию Python
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run basic checks
      run: |
        python -c "import aiogram; print(f'✅ AIogram {aiogram.__version__} installed')"
        python test_import.py
        echo "✅ All checks passed"
      
